### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by ghzgod** [JoshuaKimsey/Linux-StableDiffusion-Script#1]
Hello, first and foremost thank you for this.

I got an error during install regarding the following lines from webui.py

```
from frontend.frontend import draw_gradio_ui
from frontend.ui_functions import resize_image
```

The error was 'frontend module not found'.  I think its because its looking in the scripts folder rather than the folder before the scripts folder.

**Comment by JoshuaKimsey** [comment]
Hmm, this likely wouldn't be associated with my script so much as it would be with the main repo itself as far as I can tell. Make sure your conda env for the project was installed correctly. You can do this by by typing:

```bash
conda env remove -n lsd
cd ultimate-stable-diffusion
conda env create -f environment.yaml
``` 

If that works then I'll see is there is an issue with my script. If it still fails after that, then open an issue in the main repo of [hlky's fork](https://github.com/hlky/stable-diffusion) and we can try to figure out what's happening.

**Comment by kaneyxx** [comment]
> Hmm, this likely wouldn't be associated with my script so much as it would be with the main repo itself as far as I can tell. Make sure your conda env for the project was installed correctly. You can do this by by typing:
> 
> ```shell
> conda env remove -n lsd
> cd ultimate-stable-diffusion
> conda env create -f environment.yaml
> ```
> 
> If that works then I'll see is there is an issue with my script. If it still fails after that, then open an issue in the main repo of [hlky's fork](https://github.com/hlky/stable-diffusion) and we can try to figure out what's happening.

At first time, I have the same issue. I found the problem is that I was not in the conda environment. I solved the problem while being in the correct conda env. So just make sure you type `conda activate lsd` at first :)

**Comment by ghzgod** [comment]
> 

Yes, this worked.  thank you!

**Comment by ludrol** [comment]
StableDiffusion/linux-sd.sh: line 55: conda: command not found 
got this related error when running script a second time
prieviosly got an error on line 105.

P.S. `conda activate lsd` solved the issue
