### ISSUE TITLE
new github changed

### ISSUE THREAD

**Issue by emorytaylor** [JoshuaKimsey/Linux-StableDiffusion-Script#3]
https://github.com/sd-webui/stable-diffusion-webui

i was able to manually change the github and the filename and it worked. i did get another error that i corrected but i think it was upstream of this

**Comment by JoshuaKimsey** [comment]
I just pushed an update for this to fix it, Version 1.8. Leaves the old folder untouched, just reinstalls it in a new one, so feel free to copy your outputs over to the new one and delete `ultimate-stable-diffusion` once you do so. It's no longer needed.

**Comment by JoshuaKimsey** [comment]
This has been updated, let me know if you see any issues with it. :)
