### ISSUE TITLE
linux-setup.sh not created with 1.8

### ISSUE THREAD

**Issue by quinxy** [JoshuaKimsey/Linux-StableDiffusion-Script#5]
1.7 worked great for me, tried to run 1.8 and am getting a few things which don't seem right.  The main thing being that the script ends with:

> Customization of Ultimate Stable Diffusion is complete. Continuing...
> 
> Generating linux-setup.sh in ./stable-diffusion-webui
> ./linux-sd.sh: line 157: cd: ultimate-stable-diffusion: No such file or directory
> Running linux-setup.sh...
> **bash: ./linux-setup.sh: No such file or directory**

The other thing which seemed weird, is that at the start of the script it outputs this:

Starting Ultimate Stable Diffusion installation...

> Cloning Ultimate Stable Diffusion. Please wait...
> Cloning into 'stable-diffusion-webui'...
> remote: Enumerating objects: 1498, done.
> remote: Counting objects: 100% (1436/1436), done.
> remote: Compressing objects: 100% (628/628), done.
> remote: Total 1498 (delta 836), reused 1343 (delta 785), pack-reused 62
> Receiving objects: 100% (1498/1498), 17.69 MiB | 5.25 MiB/s, done.
> Resolving deltas: 100% (856/856), done.
> **mv: cannot stat 'stable-diffusion': No such file or directory**

Not sure if that last line is expected.

**Comment by quinxy** [comment]
Looks like line 157 just references the old directory name not the $DIRECTORY so for anyone reading this, just change 

> cd ultimate-stable-diffusion

to 

> cd $DIRECTORY

**Comment by JoshuaKimsey** [comment]
Yeah, i forgot to delete that. It should cause no harm, but I'll clean it up in a small update shortly.

**Comment by JoshuaKimsey** [comment]
The renaming part isn't actually needed anymore, I'm just using the default repo folder name now.

**Comment by JoshuaKimsey** [comment]
Ah, thanks for this! Yes, I had missed that actually, will update shortly.

**Comment by quinxy** [comment]
Right, understood, but as is it doesn't start start running post install.

BTW, thanks for the script!  Made trying out SD a lot more approachable!  And quicker.

**Comment by JoshuaKimsey** [comment]
Lol, yes sorry! I suddenly realized it was important. Fixing now x3

**Comment by JoshuaKimsey** [comment]
And you're so welcome! :)

**Comment by JoshuaKimsey** [comment]
Just fixed, let me know if there are any other issues. :)
