### ISSUE TITLE
cv2

### ISSUE THREAD

**Issue by icf20** [JoshuaKimsey/Linux-StableDiffusion-Script#7]
v 1,8
```
import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
```
cheers

**Comment by tbogdala** [comment]
I also had the same problem, right after I was asked to customize the command line parameters. I had noticed that it went pretty quickly past the part where i thought it'd have to setup the conda environment. I had linked the conda.sh into my profile.d and sourced it, but I think I needed to reboot my machine for it to get picked up by default.

**Comment by JoshuaKimsey** [comment]
Yeah, the exact place for the Conda path seems to vary based on machine. For me, it was in `.bashrc` but I know it can be placed elsewhere. You do need to exit out of the terminal once after installing Anaconda before trying to start the `linux-sd.sh` file, or else it will fail.

**Comment by JoshuaKimsey** [comment]
Did this issue resolve itself?

**Comment by luis-acos** [comment]
Had the same issue when the script was interrupted. Resolved itself by exiting the setup script, re-running, picking option 2) under:

```Do you wish to run Ultimate Stable Diffusion with the previous parameters?
(Select NO to customize or update your Ultimate Stable Diffusion setup)
1) Yes
2) No
```
This forced a build of the conda environment.

Looking at the shell script it looks like selecting 1) takes you directly to the linux_setup_script whereas 2) runs the conda_env_setup (among other things). I do not see anything in the linux_setup_script that creates the conda env, it just seems to activate the existing one.

**Comment by JoshuaKimsey** [comment]
@luis-acos Right, that's expected behavior. The idea being for those with fully running setups it provides a quick way to launch without any excess commands. I probably should include a check to make sure everything is running right before proceeding though.

**Comment by icf20** [comment]
Running v 1.9 of the script still gives the error

**Comment by JoshuaKimsey** [comment]
Hmm, did you go through the update process in the script?

**Comment by spazadaza** [comment]
> Hmm, did you go through the update process in the script?

Having the same issue, I get upto here then:

########## RUN PREVIOUS SETUP ##########

Do you wish to run Ultimate Stable Diffusion with the previous parameters?(Select NO to customize or update your Ultimate Stable Diffusion setup)1) Yes
2) No
#? 1
Starting Ultimate Stable Diffusion using previous parameters. Please wait...Generating linux-setup.sh in ./stable-diffusion-webuiRunning linux-setup.sh...Could not find conda environment: ldm
You can list all discoverable environments with `conda info --envs`.

Relauncher: Launching...
Traceback (most recent call last):
  File "scripts/webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Relauncher: Process is ending. Relaunching in 1s...
	Relaunch count: 1
Relauncher: Launching...
Traceback (most recent call last):
  File "scripts/webui.py", line 3, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
