### ISSUE TITLE
Amd card ?

### ISSUE THREAD

**Issue by tr1p0p** [JoshuaKimsey/Linux-StableDiffusion-Script#8]
There's absolutely zero mention of AMD GPU compatibility and any words on it on all readme and scripts.

So.. because there's a guide for AMD for stable-diffusion, did i assume it work ? Because it's seem it just don't and i have to build pytorch myself..

**Comment by cstueckrath** [comment]
you can use the script with amd without much problem, if you enter the env afterwards and pip3 --upgrade the torch stuff with the pytorch rocm 5.1.1 version.
If you have an unsupported card, you'll have to set an environment variable, too.

So:
1.: conda activate lsd
2.: pip3 install --upgrade torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.1.1
3.: conda deactivate
4. (optional): export HSA_OVERRIDE_GFX_VERSION=10.3.0

If this doesn't work, your system lacks the required modules. The guides will walk you through this.

**Comment by tr1p0p** [comment]
Ok thanks a lot !
