### ISSUE TITLE
How can i add some custom arguments ? (In my case --listen)

### ISSUE THREAD

**Issue by tr1p0p** [JoshuaKimsey/Linux-StableDiffusion-Script#9]
Hi, i successfully this script and all on my self-hosted machine. Now it's accessible outside with the  gradio app, but i try to simple make it accessible with my own domain name since it's installed on my host machine. But i figure it didn't work right away with only gradio. So i think i need the --listen args on startup, but i can find how i can edit the script or put some custom args.

Think it could be a great add for the script, don't know.

Thanks for this, great work, apart for the cv2 issue, it's pretty straightforward

**Comment by tr1p0p** [comment]
It's okay i found a way to solve my issue and it had nothing to do with the script. For the record, arguments can be add to relauncher.py

**Comment by JoshuaKimsey** [comment]
Lol, yes sorry just got around to seeing this. Yes, custom arguments are added through `relauncher.py` inside of the `stable-diffusion-webui/scripts` directory.

Did you also have an issue with `cv2`? I can't figure out why some are having issues with that, but it seems simply redoing the conda env steps fixes it for them, so not sure what's going on.
